version: '3'

services:
  redis-server:
    image: redis:7.4.0-alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=your_secure_password
    command: ["redis-server", "--requirepass", "your_secure_password", "--appendonly", "yes"]
    volumes:
      - ./volumes/redis_data:/data 
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "your_secure_password", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
