name: Docker Build and Push

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: |
        IMAGE_TAG=ghcr.io/${{ github.repository }}:${{ github.sha }}
        docker build -t ghcr.io/${{ github.repository }}:latest .

    - name: Push Docker image
      run: |
        IMAGE_TAG=ghcr.io/${{ github.repository }}:${{ github.sha }}
        docker push $IMAGE_TAG
        docker push ghcr.io/${{ github.repository }}:latest
        docker push ghcr.io/${{ github.repository }}:latest